services:
  - type: web
    name: quantity-management-app
    env: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html